#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Usage: h7encrypt filename [e/d]"
    exit 1
fi


FILENAME=$1
ACTION=$2


if [ "$ACTION" == "e" ]; then
    /usr/local/bin/h7encrypt-files/encrypt "$FILENAME"
elif [ "$ACTION" == "d" ]; then
    /usr/local/bin/h7encrypt-files/decrypt "$FILENAME"
else
    echo "Invalid action: $ACTION. Use 'e' for encrypt or 'd' for decrypt."
    exit 1
fi
